SportStoreCore2/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStoreCore2.Models;

namespace SportStoreCore2.Components
{
    public class CartSummaryViewComponent: ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

SportStoreCore2/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportStoreCore2.Models;
using SportStoreCore2.Models.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SportStoreCore2.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        private readonly Cart _cart;

        public CartController(IProductRepository repository, Cart cart)
        {
            _repository = repository;
            _cart = cart;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = _cart,
                ReturnUrl = returnUrl
            });
        }

        // GET: /<controller>/
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            var product = _repository.Products
                .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                _cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            var product = _repository.Products
                .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                _cart.Remove(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportStoreCore2/Views/Shared/ProductSymmary.cshtml
@model Product
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductId" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">Add to Cart</button>
        </span>

    </form>
</div>

SportStoreCore2/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>

    <script src="/lib/jquery/jquery.min.js"></script>
    <script src="/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary" asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

SportStoreCore2/Views/Shared/_Layout.cshtml
SportStore<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <title>SportStore</title>
</head>
<body>
<div class="navbar navbar-inverse bg-inverse" role="navigation"> 
    <div class="row"> 
        <a class="col navbar-brand" href="#">SPORTS STORE</a> 
        <div class="col-4 text-right"> 
            @await Component.InvokeAsync("CartSummary") 
        </div> 
    </div> 
</div> 
<div class="row m-1 p-1"> 
    <div id="categories" class="col-3">
        @await Component.InvokeAsync("NavigationMenu")
    </div> 
    <div class="col-9"> 
        @RenderBody()
    </div>
</div>
</body>
</html>